print('Olá Irei pedir alguns dados.')
dia = input ('Digite o dia do seu nascimento: ')
mes = input ('Digite o mês do seu nascimento:  ')
ano = input ('Digite o ano do seu nascimento: ')
print ('O ano do seu nascimento é: ', dia, '/' , mes,'/' ,ano)
